### ISSUE TITLE
Maximum data transfer Hz rate when using roslibpy?  

### ISSUE THREAD

**Issue by Akumar201** [gramaziokohler/roslibpy#113]
Hi, I am sending data from a non ROS software using TCP to rosbridge, after that using roslibpy to publish that data to a specific topic. I would like to know that what could be the maximum hz rate I can get the data using roslibpy? 

## System Information
I am using Ubuntu 20.04, ROS Noetic

**Comment by gonzalocasas** [comment]
This depends heavily on your specific setup, we cannot really determine an absolute max value that is generally correct. What I can say is that I've seen pretty high rates in some internal tests that were surprising to me at the time. If you do some tests yourself, it would be interesting if you could share them.

For the time being, I will close this issue because we don't have any concrete action to do on the code base. But feel free to keep the conversation going in here.
